# Generated by Django 4.1.3 on 2022-12-20 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
