# Generated by Django 4.1.3 on 2022-12-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
